apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: spotify
  description: The Spotify web API
  tags:
    - spotify
    - rest
  annotations:
    # The annotation is deprecated, we use placeholders (see below) instead, remove it later.
    backstage.io/definition-at-location: 'url:https://github.com/ayousry1/backstage-api/blob/master/onboarding/onboarding-api.yaml'
spec:
  type: openapi
  lifecycle: production
  owner: team-a
  definition:
    $text: https://github.com/ayousry1/backstage-api/blob/master/onboarding/onboarding-api.yaml
